CREATE DATABASE IF NOT EXISTS mentara CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mentara;
CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role ENUM('user','admin') NOT NULL DEFAULT 'user', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS mood_entries (
 id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, mood VARCHAR(40) NOT NULL, note VARCHAR(500) DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,created_at)
);
CREATE TABLE IF NOT EXISTS journal_entries (
 id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(150) DEFAULT 'My thoughts', content TEXT NOT NULL, mood VARCHAR(40), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,created_at)
);
CREATE TABLE IF NOT EXISTS counselors (
 id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, specialization VARCHAR(150) NOT NULL, bio TEXT, available_days VARCHAR(100), available_hours VARCHAR(100), active BOOLEAN DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS bookings (
 id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, counselor_id INT NOT NULL, booking_date DATE NOT NULL, booking_time TIME NOT NULL,
 reason VARCHAR(500), status ENUM('pending','confirmed','completed','cancelled') DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(counselor_id) REFERENCES counselors(id) ON DELETE RESTRICT,
 INDEX(counselor_id,booking_date,booking_time)
);
CREATE TABLE IF NOT EXISTS resources (
 id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(200) NOT NULL, description TEXT, category VARCHAR(80) NOT NULL, url VARCHAR(500), active BOOLEAN DEFAULT TRUE
);
